### ISSUE TITLE
启动的时候会出现这个问题

### ISSUE THREAD

**Issue by hackeryutu** [FastBootWeixin/FastBootWeixin#1]
我把maven换成gradle
然后用war包启动

org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'com.zk.weixin.config.message.WxAsyncMessageConfiguration': Unsatisfied dependency expressed through constructor parameter 1; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'wxMediaManager' defined in weixin.config.media.WxMediaConfiguration: Bean instantiation via factory method failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [weixin.module.media.WxMediaManager]: Factory method 'wxMediaManager' threw exception; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'wxMediaStore' defined in weixin.config.media.WxMediaConfiguration: Invocation of init method failed; nested exception is java.io.IOError: java.io.IOException: Wrong index checksum, store was not closed properly and could be corrupted.

**Comment by hackeryutu** [comment]
找到问题了。 WxMediaStore 里面有三个属性    

private String defaultFilePath =

private String defaultTempFilePath =

private String defaultDbPath = 

改成win下的文件路径格式就可以了

**Comment by HikariShine** [comment]
这个问题我这里也偶尔会出现
这是因为用了mapdb做内嵌式数据库，这个mapdb的文件现在只要程序非正常关闭都会报checksum不正确，需要删除对应目录下的db文件，目前准备对WxMediaStore做重构，如果有好的意见欢迎提出哈

**Comment by hackeryutu** [comment]
谢谢
