### ISSUE TITLE
公众号跳转小程序

### ISSUE THREAD

**Issue by zhengxiangchen** [FastBootWeixin/FastBootWeixin#11]
wxbutton里的type中没有发现跳转小程序的按钮类型，官方文档有按钮类型，如果能填进jar包中不需要后续再开发会方便很多。

**Comment by HikariShine** [comment]
小程序类型已加，可以使用0.6.1-SNAPSHOT版本
根据情况判断是否加入消息类型

**Comment by HikariShine** [comment]
已完成
