### ISSUE TITLE
0.6.2版本无法设置属性 wx.mvc.interceptor.include-patterns

### ISSUE THREAD

**Issue by jaiiye** [FastBootWeixin/FastBootWeixin#17]
你好，HikariShine：
fastboot-weixin 0.6.2 版本无法设置属性wx.mvc.interceptor.include-patterns。

spring boot提示信息如下：
Failed to bind properties under 'wx.mvc.interceptor' to com.mxixm.fastboot.weixin.config.WxProperties$Mvc$Interceptor:

    Reason: No setter found for property: include-patterns

Action:

Update your application's configuration

看了源码，确实是没有提供setter方法。

**Comment by HikariShine** [comment]
确实没有，感谢反馈。暂时可以使用wx.mvc.interceptor.include-patterns[0]=xxx这种方式设置，忘了当时为啥不加setter了。0.7.0版本修复此问题

**Comment by jaiiye** [comment]
好的 谢谢。

**Comment by Diamond0728** [comment]
@HikariShine 你好，
使用wx.mvc.interceptor.include-patterns[0]=xx的方式还是会提示没有setter的错误，请问0.7.0何时发布?
多谢。

**Comment by HikariShine** [comment]
> @HikariShine 你好，
> 使用wx.mvc.interceptor.include-patterns[0]=xx的方式还是会提示没有setter的错误，请问0.7.0何时发布?
> 多谢。

预计这两天发布，可以临时使用0.7.0-SNAPSHOT版本

**Comment by Diamond0728** [comment]
好的，谢谢
