### ISSUE TITLE
萌新关于用户分组的一些疑问

### ISSUE THREAD

**Issue by LauItachi** [FastBootWeixin/FastBootWeixin#5]
微信公众号的用户分组原本好像是用过Tag的管理来完成的，那么如果要实现分组推送是否可实现？
例如：
数据库DB中存在表User，用于保存用户信息：微信号，用户名称，用户类别，……
以用户类别为例，若将用户类别分为A，B，C三类，在分组推送时需要给B类用户推送消息，实现时是先通过数据库找到所有B类用户，然后给所有B类用户贴上标签X（假设表的列数大于每个用户可贴标签最大数量），然后通过微信公众号提供的API来给所有贴着X标签的用户推送信息，这样么？
————
对于（假设表的列数大于每个用户可贴标签最大数量）的解释：如果列数小的话只要把类别直接给用户贴标签就行了，但是这一般在数据库设计比较复杂的情况下都不够吧……所以提出了这样的疑问qwq
————
萌新刚刚接触微信公众号，还只注册了一个个人级别的订阅号，有些尝试可能还没有进行，当前的想法是这样，还望指点qwq

**Comment by HikariShine** [comment]
1. 关于给某个tag推送消息的
微信是有这样的api的，群发接口可以指定tagid，但是对于服务号来说，群发消息一个月只有四次机会，订阅号有30次。WxMessageTemplate.sendGroupMessage(int tagId, WxMessage wxMessage)这个方法就是推送这种消息的。
还有一种做法是使用客服消息接口定向推送到某个人，找到某个tag下的所有人，依次推送。之前我是这样做的。

**Comment by LauItachi** [comment]
嗯嗯好的qwq
最近打算做个订阅号，正在搜集资料，发现有SpringBoot的实现就赶紧Star了，等元旦后开始动工
但是如果tag数量已经用完了或者不够的时候，会有其他途径可以进行推送么，我看了接口文档里好像没有提供这样的方法……
客服消息接口定向推送到某个人——这个的次数是没有限制的么？（好像可以参考）

**Comment by HikariShine** [comment]
推送消息的三种途径
1. 群发消息。可全部、针对tag、针对用户列表进行群发，限制是服务号一个月四条。
2. 客服消息。只能针对某个用户推送，但是可以写循环发送。限制也有，只有用户与公众号有交互之后才能发送，在交互之后的48小时内，可以推送20条客服消息给用户。交互动作包括：
```
1、用户发送信息
2、点击自定义菜单（仅有点击推事件、扫码推事件、扫码推事件且弹出“消息接收中”提示框这3种菜单类型是会触发客服接口的）
3、关注公众号
4、扫描二维码
5、支付成功
6、用户维权
```
3. 模板消息，据说发送无限制，但是内容受限，只能是通过微信验证通过的模板内容才能进行发送。

**Comment by LauItachi** [comment]
好的好的，我后面自己试试，非常感谢@w@
