### ISSUE TITLE
服务器token验证失败

### ISSUE THREAD

**Issue by yinjingjiu** [FastBootWeixin/FastBootWeixin#7]
微信公众号后台服务器基本配置报token验证失败（{"base_resp":{"ret":200302,"err_msg":"verify token fail"}}），我的链接地址，自定义token都没问题。而且后台日志打印了：
c.m.f.w.service.WxBuildinVerifyService   : ======verify start======
c.m.f.w.service.WxBuildinVerifyService   : signature:b5beeebd18005cd7aa06d60c2001cb44e274d42be,timestamp:15121094832,nonce:14113480680,echostr:152911519570616039291
c.m.f.w.service.WxBuildinVerifyService   : ======verify success end======
我用的是0.3.3版的fastboot-weixin，还请作者帮忙看下

**Comment by HikariShine** [comment]
可以尝试手动调用验证请求看下返回结果，之前有个小伙伴遇到相同的问题是因为他的json处理器自动把字符串加上了双引号
