### ISSUE TITLE
请求添加对接微信公众号JS-SDK的功能

### ISSUE THREAD

**Issue by zhengxiangchen** [FastBootWeixin/FastBootWeixin#9]
wx.config({
    debug: true, // 开启调试模式,调用的所有api的返回值会在客户端alert出来，若要查看传入的参数，可以在pc端打开，参数信息会通过log打出，仅在pc端时才会打印。
    appId: '', // 必填，公众号的唯一标识
    timestamp: , // 必填，生成签名的时间戳
    nonceStr: '', // 必填，生成签名的随机串
    signature: '',// 必填，签名
    jsApiList: [] // 必填，需要使用的JS接口列表
});

对接JS需要后台传给前端appId，timestamp，nonceStr，signature。
生成签名还需要后台额外两个步骤的请求，有点麻烦。
迫切希望能对接JS功能

**Comment by HikariShine** [comment]
收到，本周末搞定哈

**Comment by HikariShine** [comment]
已完成，版本支持：0.6.0
